### ISSUE TITLE
support daterange

### ISSUE THREAD

**Issue by kanipowa** [wwilsman/Datepicker.js#4]
Support for 'regular' daterange picking option without holes in the selection.

### example
from this selection: 
![image](https://cloud.githubusercontent.com/assets/9059270/17693070/6ef737a6-639d-11e6-9938-5ef5176e006e.png)

to this range:

![image](https://cloud.githubusercontent.com/assets/9059270/17693135/a646f296-639d-11e6-8c88-ffb010525607.png)

**Comment by wwilsman** [comment]
I was actually going to be working on that at some point this week! You can see the default option for it in the source, just need to implement it. 👍

**Comment by wwilsman** [comment]
There it is. Going to be documenting this soon and updating the demo page.

**Comment by kanipowa** [comment]
thank you! great work! :)
could you publish to npm?
