### ISSUE TITLE
timepicker support

### ISSUE THREAD

**Issue by tamascsaba** [wwilsman/Datepicker.js#6]
Add timepicking options to the library would be greet :) 

Example:
http://www.daterangepicker.com/#ex2

**Comment by wwilsman** [comment]
Thought this over for a while and decided to go ahead and implement it. I'll be adding documentation and updating the demo soon.

#### TL;DR

The `time` option controls this. Setting it to `true` will enable a single time picker on non-ranged datepickers. For ranged datepickers, or setting `time: 'ranged'`, a ranged time picker will be enabled.
