### ISSUE TITLE
onUpdate callback lost

### ISSUE THREAD

**Issue by kanipowa** [wwilsman/Datepicker.js#7]
I've used the picker with the `mutliple: true` option with a custom callback.
Now with a single or ranged picking this callback lost (even the IDE highlight as an unused property).

**Comment by wwilsman** [comment]
Hey, sorry about this. Stuff might be changing frequently until this reaches 1.0. The option has been renamed to `onChange`.

**Comment by kanipowa** [comment]
it looks like in my case  the `weekStart` also renamed.
