### ISSUE TITLE
IE 10 compatibility

### ISSUE THREAD

**Issue by kaloczidev** [wwilsman/Datepicker.js#9]
The demo site isn't compatible with IE10, first of all missing dataset.
I've tried adding polyfill for that, but it doesn't solve my problem.  
result: 
`ORIGINAL EXCEPTION: Unable to get property 'value' of undefined or null reference `

**Comment by tamascsaba** [comment]
After add dataset polyfill:
```
SCRIPT438: Object doesn't support property or method 'toLowerCase' 
datepicker.js, line 1 character 17178
```

https://github.com/wwilsman/Datepicker.js/blob/master/src/helpers.js#L48

**Comment by wwilsman** [comment]
Wow, this is an old issue. I don't think I ever planned to support IE10. Since this is so old, and I probably won't fix it, I'm going to close this. Let me know if IE11 or Edge has any issues (if you're still using this package that is).
